### ISSUE TITLE
[spike] Estimate implementation of update analysis and add new data metadata to existing projects

### ISSUE THREAD

**Issue by morrisonnorman** [HumanCellAtlas/dcp#416]
[RFC](https://bit.ly/2SGM3rI)

**Comment by brianraymor** [comment]
See [AUDR 2019Q3 pre-RFC](https://docs.google.com/document/d/1vvcLLYdF1j2c85QOD5HDfW269myfGvE-xqYg9vKl-Cw) for evolving design.

**Comment by justincc** [comment]
Analysis updates RFC published. Additions still in progress - will likely not be an RFC.

**Comment by justincc** [comment]
[Analysis updates RFC](https://github.com/HumanCellAtlas/dcp-community/pull/91) oversight reviews ends on Fri 23rd August so may get approved by TA same day or a week later, in which case it slips.

As for additions, as discussed last backlog review there is a 90% case which may largely be already implemented and a 10% case which may not be worth fulfilling in favor of other priorities. However, the 90% case can only be estimated after we complete [#468](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/468) which is scheduled for the local sprint that ends post milestone 2. On the 10% case, need to consult with @lauraclarke and @morrisonnorman to get a decision as to whether this can be postponed, but since both have been on holiday this has not been possible.

For this reason this task will slip to m3.

**Comment by morrisonnorman** [comment]
The conclusion from this spike is that there are two broad tasks that cover the scope of [Add new data and metadata to existing projects (AUDR)](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/414)

[AUDR: Add new files to existing bundles](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/444) and [AUDR: add new bundles to an existing project](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/523).

Both of these items require further research on implementation (spikes) for estimation, however it is considered that [AUDR: Add new files to existing bundles](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/444) is high effort with use cases that are currently not high priority.
 
The priority of these items have been discussed with @justincc @lauraclarke and flagged to PM in an email. The proposal is to deprioritise "AUDR: Add new files to existing bundles”.
 
It was considered that there are strategic decisions to be taken wrt [AUDR: Add new files to existing bundles](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/444) that would best be supported by a face to face discussion at the next DCP meeting in October 2019. @justincc Justin will propose this session.
